
name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build (use gradlew if present, otherwise install gradle)
        shell: bash
        run: |
          if [ -f "./gradlew" ]; then
            echo "Found gradlew -> using Gradle wrapper"
            chmod +x ./gradlew
            ./gradlew assembleDebug --no-daemon
          else
            echo "No gradlew found -> installing gradle via apt"
            sudo apt-get update
            sudo apt-get install -y gradle
            gradle assembleDebug --no-daemon
          fi
        env:
          JAVA_TOOL_OPTIONS: -Xmx2g

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrainingTimer-APK
          path: app/build/outputs/apk/debug/app-debug.apk
